#
# postgres configuration
#
common: &common
  encoding: unicode
  adapter: postgresql
  host: localhost
  port: 5432
  username: pinewood
  password: pinewood

development:
  <<: *common
  database: pinewood_dev

test:
  <<: *common
  database: pinewood_test

production: 
  <<: *common
  database: pinewood_prod